/*
 * SPDX-FileCopyrightText: 2024 Roland Rusch, easy-smart solution GmbH <roland.rusch@easy-smart.ch>
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef LIBSMART_STM32NETXMQTTCLIENT_LIBSMART_CONFIG_DIST_HPP
#define LIBSMART_STM32NETXMQTTCLIENT_LIBSMART_CONFIG_DIST_HPP

#define LIBSMART_STM32NETXMQTTCLIENT

#define LIBSMART_STM32NETX_MQTT_CLIENT_THREAD_STACK_SIZE 4*1024
#define LIBSMART_STM32NETX_MQTT_CLIENT_THREAD_PRIORITY 4

#define LIBSMART_STM32NETX_MQTT_CLIENT_STACK_SIZE 2560

#define LIBSMART_STM32NETXMQTTCLIENT_MAX_TOPIC_LENGTH 255

#define LIBSMART_STM32NETXMQTTCLIENT_MAX_SUBSCRIPTIONS 10


#endif
